[CmdletBinding()]
param(
    [string]$OllamaModel = "qwen3.5",
    [string]$OllamaBaseUrl = "http://localhost:11434"
)

$ErrorActionPreference = "Stop"
$Root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$Python = Join-Path $Root ".venv\Scripts\python.exe"
$Server = Join-Path $Root "tools\local_model_mcp.py"
if (-not (Test-Path $Python)) { throw "Missing .venv. Run scripts/setup_ai.ps1 first." }

$rootToml = $Root.Replace('\','/')
$pythonToml = $Python.Replace('\','/')
$serverToml = $Server.Replace('\','/')
$config = @"
# Generated by scripts/configure_codex_mcp.ps1
[mcp_servers.thunder_local]
command = "$pythonToml"
args = ["$serverToml"]
env = { OLLAMA_BASE_URL = "$OllamaBaseUrl", OLLAMA_MODEL = "$OllamaModel", PROJECT_ROOT = "$rootToml" }
"@

New-Item -ItemType Directory -Force -Path (Join-Path $Root ".codex") | Out-Null
Set-Content -Path (Join-Path $Root ".codex\config.toml") -Value $config -Encoding utf8
Write-Host "Project MCP config written to .codex/config.toml" -ForegroundColor Green
Write-Host "Open Codex from this project root, trust the project, then run /mcp to confirm thunder_local." -ForegroundColor Cyan
